services:
  runner:
    build:
      context: .
      args:
        RUNNER_HOME: ${RUNNER_HOME:-/opt/actions-runner}
    command:
      - ./start.sh $ACCESS_TOKEN
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: any
        delay: 1s
    entrypoint: ["/bin/bash", "-c"]
    environment:
      LABELS: ${LABELS}
      ORGANISATION: ${ORGANISATION}
      RUNNER_GROUP: ${RUNNER_GROUP:-default}
      RUNNER_HOME: ${RUNNER_HOME:-/opt/actions-runner}
    healthcheck:
      test: |
        pgrep -f "run.sh" > /dev/null &&
        pgrep -f "run-helper.sh" > /dev/null &&
        pgrep -f "Runner.Listener" > /dev/null
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    network_mode: host
