services:
  runner:
    build: .
    env_file: .env
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - LABELS=${LABELS}
      - ORGANISATION=${ORGANISATION}
      - RUNNER_GROUP=${RUNNER_GROUP:-default}
    network_mode: host
    healthcheck:
      test: |
        pgrep -f "run.sh" > /dev/null &&
        pgrep -f "run-helper.sh" > /dev/null &&
        pgrep -f "Runner.Listener" > /dev/null
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: always
        delay: 1s
